services:
  postgres_me:
    image: postgres:17.5
    container_name: postgres_me
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    volumes:
      - postgres-me-data:/var/lib/postgresql/data
    ports:
      - 5437:5432
    networks:
      - local-network-me
  pgadmin_me:
    image: dpage/pgadmin4:9.5
    container_name: pgadmin_me
    depends_on:
      - postgres_me
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@laros.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8087:80
    volumes:
      - pgadmin-me-data:/var/lib/pgadmin
    networks:
      - local-network-me
volumes:
  postgres-me-data:
  pgadmin-me-data:
networks:
  local-network-me:
    driver: bridge